[build]
  command = "npm run build:web"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env.production]
  [env.production.context.production.environment]
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY = ""

[env.preview]
  [env.preview.context.preview.environment]
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY = ""

[dev]
  command = "npm run web"
  port = 3000
